import type { Metadata } from 'next'
import { Geist, Geist_Mono, Libre_Franklin } from 'next/font/google'
import './globals.css'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

const libreFranklin = Libre_Franklin({
  variable: '--font-libre-franklin',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${libreFranklin.variable} antialiased font-sans`}
      >
        {children}
      </body>
    </html>
  )
}
